name: Security Scan
on: [push]
jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4
       
     - name: Install pip-audit
       run: pip install pip-audit

     - name: Run pip-audit
       run: pip-audit || true
       
     - name: Secret scan (gitleaks)
       uses: zricethezav/gitleaks-action@v2
       with:
         args: detect --source . --no-git --redact

     - name: Setup Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'

     - name: Install Bandit
       run: pip install bandit

     - name: Run Bandit
       run: bandit -r .

     - name: Run Bandit Scan
       run: bandit -r . || true
         
