name: Security Scan
on: push
jobs:
 bandit_scan:
 runs-on: ubuntu-latest
 steps:
 -name: Checkout repo
 uses: actions/checkout@v2

 name: Setup Python
 uses: actions/setup-python@v2
 with:
 python-version: 3.x

 -name: Install Bandit
 run: pip install bandit

 -name: Run Bandit Scan
 run: bandit -r
